-- MySQL Script generated by MySQL Workbench
-- Mon Jun 13 15:06:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_109403009
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_109403009
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_109403009` DEFAULT CHARACTER SET utf8 ;
USE `db_109403009` ;

-- -----------------------------------------------------
-- Table `db_109403009`.`tblCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_109403009`.`tblCategory` (
  `id_tblCategory` INT UNSIGNED NOT NULL,
  `CategoryName_tblCategory` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tblCategory`),
  UNIQUE INDEX `id_catgory_UNIQUE` (`id_tblCategory` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403009`.`tblProposal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_109403009`.`tblProposal` (
  `id_tblProposal` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT UNSIGNED NOT NULL,
  `Title_tblProposal` VARCHAR(200) NOT NULL,
  `Content_tblProposal` VARCHAR(200) NULL,
  `Amount_tblProposal` DOUBLE UNSIGNED NULL,
  `Goal_tblProposal` DOUBLE UNSIGNED NULL,
  `Status_tblProposal` INT UNSIGNED NULL,
  `ViewedNum_tblProposal` INT UNSIGNED NULL,
  `CreateDate_tblProposal` DATE NOT NULL,
  `DueDate_tblProposal` DATE NULL,
  `IsDeactivated_tblProposal` TINYINT NULL,
  PRIMARY KEY (`id_tblProposal`),
  UNIQUE INDEX `id_tblProposal_UNIQUE` (`id_tblProposal` ASC) VISIBLE,
  INDEX `category_id_fk_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category_id_tblProposal_fk`
    FOREIGN KEY (`category_id`)
    REFERENCES `db_109403009`.`tblCategory` (`id_tblCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403009`.`tblMemberCredential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_109403009`.`tblMemberCredential` (
  `id_tblMemberCredential` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `HashedUserId_tblMemberCredential` INT UNSIGNED NOT NULL,
  `HashedPwdString_tblMemberCredential` VARCHAR(200) NULL,
  PRIMARY KEY (`id_tblMemberCredential`),
  UNIQUE INDEX `id_tblMemberCredential_UNIQUE` (`id_tblMemberCredential` ASC) VISIBLE,
  UNIQUE INDEX `HashedUserId_tblMemberCredential_UNIQUE` (`HashedUserId_tblMemberCredential` ASC) VISIBLE,
  CONSTRAINT `HashedUserId_fk`
    FOREIGN KEY (`id_tblMemberCredential`)
    REFERENCES `db_109403009`.`tblMemberCredential` (`id_tblMemberCredential`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403009`.`tblMember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_109403009`.`tblMember` (
  `id_tblMember` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name_tblMember` VARCHAR(64) NOT NULL,
  `Phone_tblMember` VARCHAR(64) NOT NULL,
  `Email_tblMember` VARCHAR(64) NOT NULL,
  `Salt_tblMember` VARCHAR(64) NULL,
  `Address_tblMember` VARCHAR(255) NULL,
  UNIQUE INDEX `Email_tblMember_UNIQUE` (`Email_tblMember` ASC) VISIBLE,
  PRIMARY KEY (`id_tblMember`),
  UNIQUE INDEX `id_tblMember_UNIQUE` (`id_tblMember` ASC) VISIBLE,
  CONSTRAINT `id_tblMember_fk`
    FOREIGN KEY (`id_tblMember`)
    REFERENCES `db_109403009`.`tblMemberCredential` (`id_tblMemberCredential`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403009`.`tblComment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_109403009`.`tblComment` (
  `id_tblComment` INT UNSIGNED NOT NULL,
  `proposal_id` INT UNSIGNED NULL,
  `member_id` INT UNSIGNED NULL,
  `UserComment_tblcomment` VARCHAR(200) NULL,
  `ProposerResponse_tblComment` VARCHAR(200) NULL,
  `CommentTime_tblComment` DATETIME NOT NULL,
  PRIMARY KEY (`id_tblComment`),
  INDEX `proposal_id_fk_idx` (`proposal_id` ASC) VISIBLE,
  INDEX `member_id_fk_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `proposal_id_tblComment_fk`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403009`.`tblProposal` (`id_tblProposal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_tblComment_fk`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_109403009`.`tblMember` (`id_tblMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403009`.`tblFAQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_109403009`.`tblFAQ` (
  `id_tblFAQ` INT NOT NULL,
  `proposal_id` INT UNSIGNED NOT NULL,
  `LastEditorId_tblFAQ` INT NULL,
  `Question_tblFAQ` VARCHAR(200) NULL,
  `Answer_tblFAQ` VARCHAR(200) NULL,
  `UpdatedAt_tblFAQ` DATETIME NOT NULL,
  PRIMARY KEY (`id_tblFAQ`),
  UNIQUE INDEX `id_tblFAQ_UNIQUE` (`id_tblFAQ` ASC) VISIBLE,
  INDEX `proposal_id_fk_idx` (`proposal_id` ASC) VISIBLE,
  CONSTRAINT `proposal_id_tblFAQ_fk`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403009`.`tblProposal` (`id_tblProposal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403009`.`tblFollowingRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_109403009`.`tblFollowingRecord` (
  `id_tblFollowingRecord` INT UNSIGNED NOT NULL,
  `proposal_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_tblFollowingRecord`),
  UNIQUE INDEX `id_tblFollowingRecord_UNIQUE` (`id_tblFollowingRecord` ASC) VISIBLE,
  INDEX `proposal_id_fk_idx` (`proposal_id` ASC) VISIBLE,
  INDEX `member_id_fk_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `proposal_id_tblFollowingRecord_fk`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403009`.`tblProposal` (`id_tblProposal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_tblFollowingRecord_fk`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_109403009`.`tblMember` (`id_tblMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403009`.`tblProposalMember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_109403009`.`tblProposalMember` (
  `id_tblProposalMember` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `proposal_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_tblProposalMember`),
  UNIQUE INDEX `id_tblProposalMember_UNIQUE` (`id_tblProposalMember` ASC) VISIBLE,
  INDEX `proposal_id_fk_idx` (`proposal_id` ASC) VISIBLE,
  INDEX `member_id_fk_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `proposal_id_tblProposalMember_fk`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403009`.`tblProposal` (`id_tblProposal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_tblProposalMember_fk`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_109403009`.`tblMember` (`id_tblMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403009`.`tblProposalOption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_109403009`.`tblProposalOption` (
  `id_tblProposalOption` INT UNSIGNED NOT NULL,
  `proposal_id` INT UNSIGNED NOT NULL,
  `Title_tblProposalOption` VARCHAR(45) NOT NULL,
  `Price_tblProposalOption` DOUBLE UNSIGNED NOT NULL,
  `Description_tblProposalOption` VARCHAR(200) NULL,
  PRIMARY KEY (`id_tblProposalOption`),
  UNIQUE INDEX `id_tblProposalOption_UNIQUE` (`id_tblProposalOption` ASC) VISIBLE,
  INDEX `proposal_id_fk_idx` (`proposal_id` ASC) VISIBLE,
  UNIQUE INDEX `proposal_id_UNIQUE` (`proposal_id` ASC) VISIBLE,
  CONSTRAINT `proposal_id_fk`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403009`.`tblProposal` (`id_tblProposal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403009`.`tblSponsorRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_109403009`.`tblSponsorRecord` (
  `id_tblSponsorRecord` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  `proposal_option_id` INT UNSIGNED NOT NULL,
  `Amount_tblSponsorRecord` DOUBLE UNSIGNED NULL,
  PRIMARY KEY (`id_tblSponsorRecord`),
  UNIQUE INDEX `id_tblSponsorRecord_UNIQUE` (`id_tblSponsorRecord` ASC) VISIBLE,
  INDEX `member_id_fk_idx` (`member_id` ASC) VISIBLE,
  INDEX `proposal_option_id_fk_idx` (`proposal_option_id` ASC) VISIBLE,
  CONSTRAINT `member_id_tblSponsorRecord_fk`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_109403009`.`tblMember` (`id_tblMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `proposal_option_id_fk`
    FOREIGN KEY (`proposal_option_id`)
    REFERENCES `db_109403009`.`tblProposalOption` (`id_tblProposalOption`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
